#!/bin/sh

ROOT=/Users/manishsingh/GoogleDrive/SEM3/devopsgit/advanced_docker/hw4_task3/Deployment/deploy/

GIT_WORK_TREE=$ROOT/blue-www/ git checkout -f

docker pull localhost:5000/hw4_task3_myapp:latest

docker stop hw4_task3_myapp_blue

docker rm hw4_task3_myapp_blue

#docker rmi hw4_task3_myapp:blue

#docker tag localhost:5000/hw4_task3_myapp:latest hw4_task3_myapp:blue

#docker run -p 9090:8080 -d --name hw4_task3_myapp_blue hw4_task3_myapp:blue
docker run -p 9090:8080 -d --name hw4_task3_myapp_blue hw4_task3_myapp:latest sh -c "node /src/main.js 8080"

#docker exec -td hw4_task3_myapp_blue sh -c "node /src/main.js 8080"


