---
- hosts: Servers
  tasks:
  - name: install nginx webserver
    sudo : true
    apt : name=nginx state=present update_cache=yes
    notify:
    - start nginx
  handlers:
    - name: start nginx
      service: name=nginx enabled=yes state=started
